name: Delete old image

on:
  - workflow_dispatch

env:
  REPO_NAME: joey-builder

permissions:
  packages: write

jobs:
  push-ghcr:
    name: Build and push image
    runs-on: ubuntu-22.04

    steps:
      - name: delete
        uses: bots-house/ghcr-delete-image-action@v1.1.0
        with:
          owner: ${{ github.repository_owner }}
          name: ${{ env.REPO_NAME }}
          token: ${{ github.token }}
