name: Create the Builder Base Image
on:
  - workflow_dispatch
env:
  IMAGE_NAME: joey-builder-base
  IMAGE_TAGS: v1 ${{ github.sha }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  push-ghcr:
    name: Build and push image
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Build Image with Docker
        id: build_image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAGS -f ./builder-base/Containerfile .
          echo "::set-output name=image::$IMAGE_NAME"
          echo "::set-output name=tags::$IMAGE_TAGS"